### ISSUE TITLE
Missing package.json files for some packages?

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-security#183]
When I turn on "require package hashes" in Stack on the Hackage Security branch, I get the following error message:

> Package index Hackage is configured to require package hashes, but no hash is available for amazonka-codedeploy-1.4.0

Sure enough, if I look in the 01-index.tar file, there is no package.json file for that release of amazonka-codedeploy:

<img width="420" alt="screen shot 2017-01-25 at 4 04 32 pm" src="https://cloud.githubusercontent.com/assets/49415/22293391/0bd545a0-e318-11e6-81b3-9535b79caeea.png">

Is there some reason for this file to be missing? From a security standpoint, it would be nice to be able to depend on the existence of a hash for every package.

Also, I'm not sure if this is the appropriate repo for this question. I can move it to the Hackage Server tracker if that's better.

**Comment by hvr** [comment]
We have known about this for quite some time already (c.f. https://github.com/haskell/hackage-server/issues/488) but this glitch is very hard to reproduce and hasn't re-occured ever since then. This is also the reason why the `hackage-mirror-tool` [needs this temporary hack](https://github.com/hvr/hackage-mirror-tool/blob/master/src/IndexShaSum.hs#L160-L181). At some point we're gonna supply those missing `package.json` files in the index tarball, we just didn't get to it yet.

**Comment by snoyberg** [comment]
Is there no method available to:

1. Manually add the missing package.json files, and
2. Add a sanity check (like each .cabal file has a package.json file) before the 01-index.tar.gz file is generated?

This does seem to significantly impede the ability of tools to provide security guarantees.

**Comment by hvr** [comment]
> This does seem to significantly impede the ability of tools to provide security guarantees.

That's not really true though because as a kind of happy accident this unintentional situation currently exercises `cabal`'s code-paths for when the package hashes are missing; and in fact `cabal` refuses to download  those couple of packages whose cryptographic checksums are missing. This just forces us to be able to cope with this exceptional case which we would have to anyway.

**Comment by tfausak** [comment]
Is there any way for me to help with this issue? It has been a known problem for a year and a half. It continues to happen as recently as a week ago. It does not seem like something that tools should have to deal with; if a `.cabal` file is in the index, a `package.json` file should be there too. 

- https://github.com/commercialhaskell/all-cabal-hashes/issues/9
- https://github.com/commercialhaskell/all-cabal-hashes/issues/11
- https://github.com/commercialhaskell/all-cabal-hashes/issues/12
- https://github.com/commercialhaskell/all-cabal-hashes/issues/15
- https://github.com/haskell/cabal/issues/4828
- https://github.com/haskell/hackage-server/issues/488
- https://github.com/haskell/hackage-server/issues/570
- https://github.com/haskell/hackage-server/issues/573
- https://github.com/haskell/hackage-server/issues/623
- https://github.com/hvr/hackage-mirror-tool/issues/2

**Comment by tfausak** [comment]
It's hard to tell how often this happens because the original report (https://github.com/haskell/hackage-server/issues/488) has been edited, but these are the packages that are currently affected by this problem:

- [amazonka-codedeploy-1.4.0](https://hackage.haskell.org/package/amazonka-codedeploy-1.4.0)
- [amazonka-config-1.3.5](https://hackage.haskell.org/package/amazonka-config-1.3.5)
- [amazonka-importexport-1.3.7](https://hackage.haskell.org/package/amazonka-importexport-1.3.7)
- [amazonka-importexport-1.4.0](https://hackage.haskell.org/package/amazonka-importexport-1.4.0)
- [amazonka-s3-1.3.6](https://hackage.haskell.org/package/amazonka-s3-1.3.6)
- [amazonka-sdb-1.4.0](https://hackage.haskell.org/package/amazonka-sdb-1.4.0)
- [eventloop-0.5.0.0](https://hackage.haskell.org/package/eventloop-0.5.0.0)
- [gi-gdkpixbuf-0.2.31.12](https://hackage.haskell.org/package/gi-gdkpixbuf-0.2.31.12)
- [gi-gio-0.2.46.13](https://hackage.haskell.org/package/gi-gio-0.2.46.13)
- [gi-girepository-0.1.44.12](https://hackage.haskell.org/package/gi-girepository-0.1.44.12)
- [glue-ekg-0.4.4](https://hackage.haskell.org/package/glue-ekg-0.4.4)
- [gnuidn-0.2.2](https://hackage.haskell.org/package/gnuidn-0.2.2)
- [gogol-admin-reports-0.2.0](https://hackage.haskell.org/package/gogol-admin-reports-0.2.0)
- [gogol-autoscaler-0.0.1](https://hackage.haskell.org/package/gogol-autoscaler-0.0.1)
- [hops-0.4.0](https://hackage.haskell.org/package/hops-0.4.0)
- [hprotoc-2.1.11](https://hackage.haskell.org/package/hprotoc-2.1.11)
- [hzaif-0.1.0.0](https://hackage.haskell.org/package/hzaif-0.1.0.0)
- [repa-io-3.4.0.2](https://hackage.haskell.org/package/repa-io-3.4.0.2)
- [wai-middleware-prometheus-0.2.0](https://hackage.haskell.org/package/wai-middleware-prometheus-0.2.0)

Generated with https://gist.github.com/tfausak/ed463c32638b8bd876df1a0712fc88bd.

**Comment by snoyberg** [comment]
@tfausak That looks like to lines up with the list from hackage-mirror-tool: https://github.com/snoyberg/hackage-mirror-tool/blob/213064e4dd5983d01b6c7daa1c7eb37bed5255fd/src/IndexShaSum.hs#L165

**Comment by snoyberg** [comment]
Looks like aivika-transformers-5.3.1.tar.gz needs to be added to the list.

**Comment by tfausak** [comment]
As @snoyberg mentioned, [aivika-transformers-5.3.1](https://hackage.haskell.org/package/aivika-transformers-5.3.1) is missing its `package.json`. It was uploaded at 2017-10-27T04:35:54Z.

Also this just happened again with [llvm-hs-5.1.1](https://hackage.haskell.org/package/llvm-hs-5.1.1) (https://github.com/haskell/hackage-server/issues/643). That one was uploaded at 2017-12-16T14:00:07Z.

**Comment by gbaz** [comment]
This is resolved with https://github.com/haskell/hackage-server/issues/488

**Comment by snoyberg** [comment]
Can you clarify how this resolved the issue? It seems like this is a one
time fix-up, but doesn't solve the underlying cause, meaning this may recur
in the future. I'd be happy to hear that the underlying cause was fixed too
(and frankly would be really interested in learning what the problem is).

**Comment by gbaz** [comment]
The underlying cause was fixed in https://github.com/haskell/hackage-server/pull/644

Before, insertion of the package into the packagedb occurred and _then_ hackage security data was added to the db, in two steps. So it was possible a thread could die or the server could fall-over between the steps. That change made sure that either both changes happened or neither change happened.

**Comment by snoyberg** [comment]
Awesome, thanks!
