### ISSUE TITLE
Timing of next release

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-security#209]
Moving question from https://github.com/haskell/hackage-security/pull/202#issuecomment-365635050, which did not receive an answer.

What is the expected timing of a new release of hackage-security to Hackage? The current version of Hackage has bugs which are negatively impacting both cabal-install and Stack. See also: https://github.com/commercialhaskell/stack/pull/3865/

**Comment by hvr** [comment]
I intend to release this in time for the upcoming cabal-2.2 (which is intended to be released in 1-2 weeks;  due to GHC 8.4 which requires cabal-2.2). There's a few other loose ends in lib:hackage-security I need to look at and I need to do test the new fallback code on AIX and Solaris (and I also don't want to rush a release only to have to push out a follow-up release a week later).

**Comment by snoyberg** [comment]
That makes sense, thank you for clarifying. We'll move ahead with pinning
to a commit in Stack in the interim.

**Comment by snoyberg** [comment]
Since Cabal 2.2 has been released but this hasn't, reopening to more clarification if you don't mind. The next Stack release depends on both hackage-security and Cabal 2.2, and if this isn't released to Hackage we'll need to ship with an unofficial release, leading to likely behavior mismatch with other distributions.

**Comment by hvr** [comment]
A little bit more patience; `exe:cabal` needs `hackage-security` as well, which is what I meant when I wrote "cabal-2.2" (note the capitalisation). ETA: early next week

**Comment by snoyberg** [comment]
Thanks for the update.

**Comment by tuncer** [comment]
Hasn't this been resolved via https://hackage.haskell.org/package/hackage-security-0.5.3.0?

**Comment by hvr** [comment]
@tuncer indeed!
