### ISSUE TITLE
New Hackage release for GHC 8.8

### ISSUE THREAD

**Issue by DanielG** [haskell/hackage-security#229]
hackage-security is currently blocking `cabal-install` bootstrapping with GHC 8.8.1, ~~the release on hackage (0.5.3.0) still seems to build fine with 8.8 though after adjusting the `base` upper bound~~.

EDIT: Nope, I was wrong. It doesn't build. So we really need a new release.

Could someone please bump the `base` bound on Hackage?

**Comment by hvr** [comment]
@DanielG it's more tricky than that; we need a new major version of hackage-security, and we've identified more things that need fixing; the new major version of hackage-security will also require a new release of `cabal-install` to be compatible with; thus `cabal-install-3.0.0.0`  will *not* be  compatible with GHC 8.8.1

**Comment by DanielG** [comment]
I don't understand why a new release is needed, can you elaborate?

haskell/cabal#6280 is also blocking on this.

**Comment by hvr** [comment]
after a brief off-issue-tracker convo with Daniel it became apparent this was a bit of a miscommunication issue due to lack of information; basically the release on Hackage has no chance to work w/ GHC 8.8.1; and in order to make hackage-security compatible a breaking change was needed which demands a major ver bump; and also #228 requires some additional semantic changes to hackage-security to warrant a new major ver of hackage-security

**Comment by hvr** [comment]
Release will be addressed in concert with haskell/cabal#6328; i.e. sometime next week

**Comment by phadej** [comment]
As far as I can see, can we have a release, so we can continue with `cabal-install`?

**Comment by hvr** [comment]
http://hackage.haskell.org/package/hackage-security-0.6.0.0
